### ISSUE TITLE
Bugs in autocomplete

### ISSUE THREAD

**Issue by bkj** [bkj/penny#15]
Autocomplete should attempt to complete the entered value as it is typed, and return should submit the query.  Currently, autocomplete does not appear until the user hits `return`.

**Comment by bkj** [comment]
(See master branch for expected functionality)

**Comment by MorganPeterson** [comment]
This feature has been disabled due to issue #16. Once the bug is patched this feature will be re-enabled.

**Comment by MorganPeterson** [comment]
Re-implemented now that issue #16 is resolved.
